fn_args_layout = "Compressed" 
max_width = 100
merge_derives = true
newline_style = "Unix"
reorder_imports = true
reorder_modules = true
tab_spaces = 2
use_field_init_shorthand = true
fn_call_width = 95
chain_width = 95